mysql:
  mode: mysql
  host: localhost
  port: 3306
  database: pairedmaps
  username: root
  password: ''
  pool-size: 5

update-interval-ticks: 1
dot-scale: 0.1
player-dot-color: "#FF0000"
item-dot-color: "#FFFFFF"
item-flash-threshold-ticks: 60
death-effect-duration-ticks: 60

player-head-dots: false
item-dots: true
terrain-render: false
terrain-samples-per-axis: 20
terrain-dot-scale: 0.08
death-effect: true
explosion-ring: true

aspect-ratio-epsilon: 0.05
